{
  "app": "exli-db",
  "primary_region": "ams",

  "env": {
    "PRIMARY_REGION": "ams"
  },

  "mounts": [
    {
      "source": "pg_data",
      "destination": "/data"
    }
  ],

  "services": [
    {
      "protocol": "tcp",
      "internal_port": 5432,
      "auto_start_machines": false,

      "ports": [
        {
          "port": 5432,

          "handlers": [
            "pg_tls"
          ]
        }
      ],

      "concurrency": {
        "type": "connections",
        "hard_limit": 1000,
        "soft_limit": 1000
      }
    },
    {
      "protocol": "tcp",
      "internal_port": 5433,
      "auto_start_machines": false,

      "ports": [
        {
          "port": 5433,

          "handlers": [
            "pg_tls"
          ]
        }
      ],

      "concurrency": {
        "type": "connections",
        "hard_limit": 1000,
        "soft_limit": 1000
      }
    }
  ],

  "checks": {
    "pg": {
      "port": 5500,
      "type": "http",
      "interval": "15s",
      "timeout": "10s",
      "path": "/flycheck/pg"
    },

    "role": {
      "port": 5500,
      "type": "http",
      "interval": "15s",
      "timeout": "10s",
      "path": "/flycheck/role"
    },

    "vm": {
      "port": 5500,
      "type": "http",
      "interval": "15s",
      "timeout": "10s",
      "path": "/flycheck/vm"
    }
  },

  "metrics": [
    {
      "port": 9187,
      "path": "/metrics"
    }
  ]
}
